function paths = detectInit()

%% Detection Dataset Paths

dnames = {'voc2012subset','voc2007','ikeaobject'};
ssboxes = {'../torch_new/mathieu_chairs/mathieu_chairs_ss_bboxes.mat',...
    '/home/francisco/work/libraries/rcnn/data/selective_search_data/voc_2007_test.mat',...
    '/media/francisco/7b0c9380-7b14-4999-a0d4-a91d079a151c/datasets/IKEA3D/ikea_object/ss_boxes.mat'};

%% CAD Dataset Paths
cnames = {'cvprchairs','ikeaobject','peng'};
%cnames = {'check_mathieu','ikeaobject','peng','francisco_normals_chair','mathieuCVPR2014_normals'};

cadfolds = {'/media/francisco/7b0c9380-7b14-4999-a0d4-a91d079a151c/datasets/chairs_aubry/processed_tight/',...
    '/media/francisco/7b0c9380-7b14-4999-a0d4-a91d079a151c/datasets/IKEA3D/crops/sphere_renders_perspective_object_new/',...
    '/media/francisco/45c5ffa3-52da-4a13-bdf4-e315366c2bdb/francisco/datasets/ICLR2015/W-UG_tight/',...
    '/media/francisco/45c5ffa3-52da-4a13-bdf4-e315366c2bdb/francisco/datasets/francisco_normals_chair',...
    '/media/francisco/45c5ffa3-52da-4a13-bdf4-e315366c2bdb/francisco/datasets/mathieuCVPR2014_normals'};

% to select the indexes corresponding to different classes
clsElms = {@(imlist,cl) true(1,length(imlist)),...
    @(imlist,cl)cellfun(@(x) ~isempty(strfind(x,cl)), imlist),...
    @(imlist,cl)cellfun(@(x) ~isempty(strfind(x,cl)), imlist),...
    @(imlist,cl) true(1,length(imlist)),...
    @(imlist,cl) true(1,length(imlist))};

%% create structure holding everything

paths = struct();
paths.testDataset = struct();
paths.cadDataset = struct();

for i=1:length(dnames),
    dname = dnames{i};
    paths.testDataset.(dname) = struct();
    paths.testDataset.(dname).ssBoxesFile = ssboxes{i};
end

for i=1:length(cnames),
    cname = cnames{i};
    paths.cadDataset.(cname) = struct();
    paths.cadDataset.(cname).folder = cadfolds{i};
    paths.cadDataset.(cname).getClassElms = clsElms{i};
end

%% ikea conversion table
% only needed because the folder with the renders have different names than
% the ones in the groundtruth

fold_list = {'lack_table_3_obj0_object',...
    'billy_bookcase_1_obj0_object',...
    'malm_bed_2_obj0_object'...
    '17119ede9322092c2b5fb024f65f6da_obj0_object',...
    '3fcb0aaa346bd46f11e76965808086c8_obj0_object',...
    'billy_bookcase_4_obj0_object',...
    'malm_bed_1_obj0_object',...
    'billy_bookcase_3_obj0_object',...
    'billy_bookcase_2_obj0_object',...
    '24abfbc0942cbf8fc8b7874340ccdda3_obj0_object',...
    '1d558bed3e89f8e0e4edfe667419c289_obj0_object',...            
};

%ikeaMap = containers.Map;
%ikeaMap('')
